### ISSUE TITLE
No suitable memory type exception on ResizableBuffer

### ISSUE THREAD

**Issue by shanto462** [generatives/Wrecker#4]
Veldrid.VeldridException: 'No suitable memory type.
I am getting this exception on ResizableBuffer Update method.

**Comment by generatives** [comment]
Does this happen every time you start the game?

**Comment by generatives** [comment]
Could you provide a stack trace?

**Comment by shanto462** [comment]
> Does this happen every time you start the game?

yes It happens everytime I start.

**Comment by shanto462** [comment]
> Could you provide a stack trace?

at Veldrid.Vk.VulkanUtil.FindMemoryType(VkPhysicalDeviceMemoryProperties memProperties, UInt32 typeFilter, VkMemoryPropertyFlags properties)
   at Veldrid.Vk.VkDeviceMemoryManager.Allocate(VkPhysicalDeviceMemoryProperties memProperties, UInt32 memoryTypeBits, VkMemoryPropertyFlags flags, Boolean persistentMapped, UInt64 size, UInt64 alignment, Boolean dedicated, VkImage dedicatedImage, VkBuffer dedicatedBuffer)
   at Veldrid.Vk.VkBuffer..ctor(VkGraphicsDevice gd, UInt32 sizeInBytes, BufferUsage usage, String callerMember)
   at Veldrid.Vk.VkResourceFactory.CreateBufferCore(BufferDescription& description)
   at Veldrid.ResourceFactory.CreateBuffer(BufferDescription& description)
   at Veldrid.ResourceFactory.CreateBuffer(BufferDescription description)
   at Clunker.Graphics.ResizableBuffer`1.Update(Span`1 data) in D:\Trunk\F\Wrecker-master\Clunker\Graphics\ResizableBuffer.cs:line 60
   at Clunker.Voxels.Meshing.VoxelGridMesher.Update(Double state, Entity& entity) in D:\Trunk\F\Wrecker-master\Clunker\Voxels\Meshing\VoxelGridMesher.cs:line 111
   at DefaultEcs.System.AEntitySystem`1.Update(T state, ReadOnlySpan`1 entities)
   at DefaultEcs.System.AEntitySystem`1.Runnable.Run(Int32 index, Int32 maxIndex)
   at DefaultEcs.Threading.DefaultParallelRunner.Run(IParallelRunnable runnable)
   at DefaultEcs.System.AEntitySystem`1.Update(T state)
   at Clunker.Scene.Update(Double deltaSec) in D:\Trunk\F\Wrecker-master\Clunker\Scene.cs:line 114
   at Clunker.ClunkerClientApp.<>c__DisplayClass36_0.<Start>b__0() in D:\Trunk\F\Wrecker-master\Clunker\ClunkerClientApp.cs:line 125
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

this is the stack trace

**Comment by generatives** [comment]
Thanks! Could you tell me what OS and version you are running on? This does not happen to me when I run the game.

**Comment by shanto462** [comment]
I am on Windows 10 Pro 20H2 OS Build 19042.985.
